name: Clone GitLab Repo

on:
  push:
    branches:
      - main

jobs:
  clone-gitlab-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v3

    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git

    - name: Enable Debugging
      run: export ACTIONS_STEP_DEBUG=true
      
    - name: Clone GitLab Repository
      env:
        GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
      run: |
        git clone https://oauth2:glpat-8V1AJkKvHDPHjc2uE9-x@gitlab.com/Atharok/BtRemote.git
