name: Flutter CI/CD on macOS

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    name: Build, Test, and Publish
    runs-on: self-hosted  # Use the self-hosted runner (macOS)

    steps:
      # Step 1: Clone GitLab Repository
      - name: Clone GitLab Repository
        env:
          GITLAB_ACCESS_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: |
          git clone https://gitlab-ci-token:${GITLAB_ACCESS_TOKEN}@gitlab.com/selviragu09/codelabflutterdemo.git
          cd CodelabFlutterDemo


      # Step 2: Set up Flutter
      - name: Set up Flutter
        run: |
          export PATH=/Users/aswathaman.ragunatha/WorkSpace/flutter/bin:$PATH
          flutter channel stable
          flutter upgrade
          flutter doctor

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: Analyze the code
      - name: Analyze Code
        run: flutter analyze

      # Step 5: Run tests
      - name: Run Tests
        run: flutter test

      # Step 6: Validate the build
      - name: Validate Build
        run: flutter build android --debug

      # Step 7: Publish to Dart
      - name: Publish to Dart
        env:
          PUB_TOKEN: ${{ secrets.PUB_TOKEN }}
        run: |
          echo $PUB_TOKEN > ~/.pub-cache/credentials.json
          flutter pub publish --force
